pipeline {
    agent any

    tool{
        maven 'maven 3.6.1'
    }

    stages {
        stage('build') {
            steps {
                echo 'Compiling Worker App...'
                dir('worker'){
                    sh 'mvn compile'
                }  
            }
        }
        stage('test') {
            steps {
                echo 'Running Unit Tets on worker app'
                dir('worker'){
                    sh 'mvn clean test'
                }  
            }
        }
        stage('package') {
            steps {
                echo 'Packaging worker app'
                dir('worker'){
                    sh 'mvn package'
                }  
            }
        }
    }
    post{
        always{
            echo ' build Pipeline multibranch for worker is completed ...'
        }
    }
}

